### ISSUE TITLE
Issues with AnnotationSubStore

### ISSUE THREAD

**Issue by tenzin3** [annotation/stam#31] opened 2024-09-12 07:07 UTC
### Issues with the new `AnnotationSubStore`

1. **Location of annotation data**:  
   When creating annotations in the `AnnotationStore` based on those contained in the `AnnotationSubStore` using an annotation selector, the annotation data is being stored in the `AnnotationSubStore` instead of the `AnnotationStore`.

2. **`AnnotationStore` annotations function**:  
   The `annotations` function in `AnnotationStore` is working correctly, but it is also retrieving annotations from the `AnnotationSubStore`.

3. **`@include` path**:  
   For our project, due to our defined data folder structure, we need to store the base file and annotation store files in separate folders. Instead of saving the `AnnotationStore` directly using `set_filename` and `save`, we convert the annotations to a JSON string using `to_json_string` and then modify the path to a relative format like `../../base/7906.txt`. This allows us to keep files in different folders and improves usability. However, in `AnnotationSubStore`, when we use `to_json_string` from `AnnotationStore`, the dependency in `AnnotationSubStore`, where we have modified the `@include` paths(resource path and AnnotationSubStore path) to relative ones, is automatically being converted back to absolute paths.

4. **Unable to load `AnnotationStore` with multi-layer `AnnotationSubStore`**:  
   When attempting to load an `AnnotationStore` with multiple layers of `AnnotationSubStore`, it fails with the error `stam.PyStamError: [StamError] DeserializationError: Deserialization failed: Expected string or array for @include in AnnotationStore.`

**Comment by tenzin3** [comment] 2024-09-12 07:08
[ID00AC0A6.zip](https://github.com/user-attachments/files/16974919/ID00AC0A6.zip)

**Comment by tenzin3** [comment] 2024-09-12 07:29
@proycon , I have got some issues with AnnotationSubStore and would like to get your thoughts and opinion.

**Comment by proycon** [comment] 2024-09-16 09:35
Thanks for the extensive feedback, I'm looking into the issues and will get back to you shortly!

**Comment by proycon** [comment] 2024-09-16 09:46
> 2 AnnotationStore annotations function:
> The annotations function in AnnotationStore is working correctly, but it is also retrieving annotations from the AnnotationSubStore.

Right, this was by design, but what was missing in the API was a method to indeed retrieve annotations that are not in any substore. I'm expanding the API so you can do that.

**Comment by tenzin3** [comment] 2024-09-16 11:03
> > 2 AnnotationStore annotations function:
> > The annotations function in AnnotationStore is working correctly, but it is also retrieving annotations from the AnnotationSubStore.
> 
> Right, this was by design, but what was missing in the API was a method to indeed retrieve annotations that are not in any substore. I'm expanding the API so you can do that.

@proycon , thank you . That would be really helpful.

**Comment by proycon** [comment] 2024-09-16 13:28
@tenzin3 This isn't really related to the current issue, but whilst looking at your data I noticed duplicate data entries in the set "Root_Commentary" in tsawa.json:

Excerpt from `stam info --verbose tsawa.json`:

```
    - [0] Set ID: "Root_Commentary"; filename: "(none)", #keys: 3; #data: 25, memory estimate: 5.27 KiB
        - [0] Key ID: "chapter_number"; #data: 2
        - [1] Key ID: "chapter_name"; #data: 2
        - [2] Key ID: "Structure_Type"; #data: 21
        - [0] Data ID: "9dbc6adaebe849cd80dbbd115811e10c"; Key: "chapter_number"; Value: String("1"); #annotations: 1
        - [1] Data ID: "8a7ea22509344dab80b0df96b1b4064d"; Key: "chapter_name"; Value: String("བ\u{fb1}ང་ཆ\u{f74}བ་ས\u{f7a}མས་ཀ\u{fb1}\u{f72}་ཕན་ཡ\u{f7c}ན་བཤད་པ།"); #annotations: 1
        - [2] Data ID: "1cc66b61f6524ef193e451afdd30dc14"; Key: "Structure_Type"; Value: String("Chapter"); #annotations: 2
        - [3] Data ID: "0afa4967f29c45869154db4549f44b8b"; Key: "chapter_number"; Value: String("2"); #annotations: 1
        - [4] Data ID: "9328e734375d4e1293b30af413b4e4e2"; Key: "chapter_name"; Value: String("ས\u{fa1}\u{f72}ག་པ་བཤགས་པ།"); #annotations: 1
        - [5] Data ID: "cb9d82f4a70140b6823bd9d56190ec74"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [6] Data ID: "f1650b46617d458194befe5e97cd3746"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [7] Data ID: "248706f1c234446e8d6bf47f69a0ff3d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [8] Data ID: "63379a4e9aea421dba043b39c80e5203"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [9] Data ID: "5a0ecd7ca7844a098ed77a52f378c6ad"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [10] Data ID: "68c625669f3f42b5a95ed3fc18ca97b3"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [11] Data ID: "083133562dec4f629420656ebd5a4420"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [12] Data ID: "aa1caaf77eff4c0b8f7c9ecd239c543d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [13] Data ID: "73e317985e7b4396baf5297fde90e931"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [14] Data ID: "059d9bbf6c014b349037c00e65f64c4b"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [15] Data ID: "ddb9c5ec36034c70bcc1a1b6c3057356"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [16] Data ID: "3cf9c2b33cc345969048ed26c86f616f"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [17] Data ID: "30b7df727ca74f16a9ecce32fcf288de"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [18] Data ID: "05c997649c58452c94b1004a40d72c8d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [19] Data ID: "72c5bf592cba4546812d8ed554272d54"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [20] Data ID: "fff1132c0c9a4277a620f3f6ff283d82"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [21] Data ID: "cd3cefe0653e4c799e85cb9216e83610"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [22] Data ID: "5ba947bc13b44c799853a93d3af15a24"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [23] Data ID: "240d1af946e84d8e9d9b815c6be0e151"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
        - [24] Data ID: "1aa6d8b2224143c6a5ac54cc8552224d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 5
```

The key/value pair *Structure_Type -> Tsawa* occurs multiple times whereas
there should be only one entry. I think this is because you may have assigned
explicit randomly generated data identifiers for those? (If you didn't then it
may be a bug on my end). If you don't specify a data ID, STAM will assign a
random data identifier for you automatically and will also ensure existing
entries are reused.

**Comment by proycon** [comment] 2024-09-16 14:03
> 1 Location of annotation data:
> When creating annotations in the AnnotationStore based on those contained in the AnnotationSubStore using an annotation 
> selector, the annotation data is being stored in the AnnotationSubStore instead of the AnnotationStore.

@tenzin3 Do you have an example of this, perhaps in the three JSON files you already provided?

After fixing some of the issues, I do run into the problem that `Tsikhang.json`
refers to annotation data ID `4f36b31e89814e80a8f9f81adb7a7904` in the set
"Root_Commentary". The set "Root Commentary" is defined in store
`Chapter-7ba.json`, but defines no data with that ID. Therefore, loading
`Tsikhang.json` still fails. I wonder if this is an instance of your issue number 1 ?

Could you point me at the code you used to create these files? That may provide
some further insight into figuring out why things go wrong.

**Comment by tenzin3** [comment] 2024-09-17 07:08
> @tenzin3 This isn't really related to the current issue, but whilst looking at your data I noticed duplicate data entries in the set "Root_Commentary" in tsawa.json:
> 
> Excerpt from `stam info --verbose tsawa.json`:
> 
> ```
>     - [0] Set ID: "Root_Commentary"; filename: "(none)", #keys: 3; #data: 25, memory estimate: 5.27 KiB
>         - [0] Key ID: "chapter_number"; #data: 2
>         - [1] Key ID: "chapter_name"; #data: 2
>         - [2] Key ID: "Structure_Type"; #data: 21
>         - [0] Data ID: "9dbc6adaebe849cd80dbbd115811e10c"; Key: "chapter_number"; Value: String("1"); #annotations: 1
>         - [1] Data ID: "8a7ea22509344dab80b0df96b1b4064d"; Key: "chapter_name"; Value: String("བ\u{fb1}ང་ཆ\u{f74}བ་ས\u{f7a}མས་ཀ\u{fb1}\u{f72}་ཕན་ཡ\u{f7c}ན་བཤད་པ།"); #annotations: 1
>         - [2] Data ID: "1cc66b61f6524ef193e451afdd30dc14"; Key: "Structure_Type"; Value: String("Chapter"); #annotations: 2
>         - [3] Data ID: "0afa4967f29c45869154db4549f44b8b"; Key: "chapter_number"; Value: String("2"); #annotations: 1
>         - [4] Data ID: "9328e734375d4e1293b30af413b4e4e2"; Key: "chapter_name"; Value: String("ས\u{fa1}\u{f72}ག་པ་བཤགས་པ།"); #annotations: 1
>         - [5] Data ID: "cb9d82f4a70140b6823bd9d56190ec74"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [6] Data ID: "f1650b46617d458194befe5e97cd3746"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [7] Data ID: "248706f1c234446e8d6bf47f69a0ff3d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [8] Data ID: "63379a4e9aea421dba043b39c80e5203"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [9] Data ID: "5a0ecd7ca7844a098ed77a52f378c6ad"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [10] Data ID: "68c625669f3f42b5a95ed3fc18ca97b3"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [11] Data ID: "083133562dec4f629420656ebd5a4420"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [12] Data ID: "aa1caaf77eff4c0b8f7c9ecd239c543d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [13] Data ID: "73e317985e7b4396baf5297fde90e931"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [14] Data ID: "059d9bbf6c014b349037c00e65f64c4b"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [15] Data ID: "ddb9c5ec36034c70bcc1a1b6c3057356"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [16] Data ID: "3cf9c2b33cc345969048ed26c86f616f"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [17] Data ID: "30b7df727ca74f16a9ecce32fcf288de"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [18] Data ID: "05c997649c58452c94b1004a40d72c8d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [19] Data ID: "72c5bf592cba4546812d8ed554272d54"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [20] Data ID: "fff1132c0c9a4277a620f3f6ff283d82"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [21] Data ID: "cd3cefe0653e4c799e85cb9216e83610"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [22] Data ID: "5ba947bc13b44c799853a93d3af15a24"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [23] Data ID: "240d1af946e84d8e9d9b815c6be0e151"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 0
>         - [24] Data ID: "1aa6d8b2224143c6a5ac54cc8552224d"; Key: "Structure_Type"; Value: String("Tsawa"); #annotations: 5
> ```
> 
> The key/value pair _Structure_Type -> Tsawa_ occurs multiple times whereas there should be only one entry. I think this is because you may have assigned explicit randomly generated data identifiers for those? (If you didn't then it may be a bug on my end). If you don't specify a data ID, STAM will assign a random data identifier for you automatically and will also ensure existing entries are reused.

@proycon . I do specify the data ID, and we assign a random UUID for that. The duplication likely occurred because I was testing multiple times to create Tsawa.json from Chapter-7ba.json.

Initially, the Chapter.json file doesn’t contain the annotation data for 'Tsawa'. We only generate that annotation data when creating Tsawa.json, but the annotation data is being stored in the Chapter file instead of Tsawa.And that’s why the annotation sets in Tsawa.json are empty.

**Comment by tenzin3** [comment] 2024-09-17 07:13
> > 1 Location of annotation data:
> > When creating annotations in the AnnotationStore based on those contained in the AnnotationSubStore using an annotation
> > selector, the annotation data is being stored in the AnnotationSubStore instead of the AnnotationStore.
> 
> @tenzin3 Do you have an example of this, perhaps in the three JSON files you already provided?
> 
> After fixing point 4, I do run into the problem that `Tsikhang.json` refers to annotation data ID `4f36b31e89814e80a8f9f81adb7a7904` in the set "Root_Commentary". The set "Root Commentary" is defined in store `Chapter-7ba.json`, but defines no data with that ID. Therefore, loading `Tsikhang.json` still fails. I wonder if this is an instance of your issue number 1 ?
> 
> Could you point me at the code you used to create these files? That may provide some further insight into figuring out why things go wrong.

@proycon 
[This is](https://github.com/OpenPecha/toolkit-v2/blob/feat/pecha-ann-on-parent-ann-store-parser/tests/pecha/parser/plaintext/plaintext_parser/ann_on_text/test_parse.py#L15) where the Chapter.json file is created.
[This is](https://github.com/OpenPecha/toolkit-v2/blob/feat/pecha-ann-on-parent-ann-store-parser/tests/pecha/parser/plaintext/plaintext_parser/ann_on_ann/test_ann_on_ann_parse.py#L18) where the Tsawa and Tsikhang JSON files are created.

**Comment by proycon** [comment] 2024-09-22 21:41
I have just released [stam-python v0.9.1](https://github.com/annotation/stam-python/releases/tag/v0.9.1)
(building on a new stam-rust v0.16.2) which incorporates various fixes for this
issue.

It took a bit longer than expected, but I had to refactor quite some of the
file-loading logic so it better handles relative paths. You should now no
longer need to use to_json_string and do manual postprocessing (in fact, that's
discouraged even), just let STAM handle it.

The STAM specification itself (v1.1.1) has also seen a slight change regarding
the `@include` mechanism and relative paths. You may want to check the exact
wording in [this commit](https://github.com/annotation/stam/commit/75229552933cbcda1c89db6e6950d6c6600f0c6a).

All relative includes are now interpreted relative to whereever the store that
is doing the include is located, or otherwise to a specifically specified work
directory in the configuration, or as final fallback to the process' current
working directory.

This also applies to filenames you set for substores, annotation sets, and text
resources, using `set_filename()` etc. They will be interpreted relative to the
store's path.

I worked out a test case that shares many similarities with your use-case. It
uses stand-off files for everything, relative paths, and demonstrates the use
of multiple layers of substores. Please check out [this code](https://github.com/annotation/stam-python/blob/master/test.py#L694).

There are now also more API methods for inspecting substores. Given an
`Annotation` instance, you can do `substore()` to get the substore it is in.
Given a `TextResource` or `AnnotationDataSet` instance you can do `substores()`
to get the substores it is in (as those can be in multiple).

To retrieve annotations in the root store and not in any substore, you can now do
`store.annotation(substore=False)`. 

This should hopefully solve all four points, I'm a little bit unsure of the
first one still but the tests I did so far on the new version seem to hold.

Further testing may still be needed on Windows systems, as I'm not entirely
confident all the file loading logic works there.

**Comment by tenzin3** [comment] 2024-09-23 03:50
@proycon . Thank you for listening to our issues and act on it quickly. I would the checkout the newest version and get back at you.

**Comment by proycon** [comment] 2024-09-23 11:27
(closing this one, let's make a new issue if there are still problems after the latest release)

**Closed by proycon** 2024-09-23 11:27 UTC
Labels: bug
